# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
osx_image: xcode12
julia:
  - 1.4
  - 1.5
  - nightly
notifications:
  email: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
