[publish_theme_default]
git-tree-sha1 = "c4a004c05b3da9ee9916ef375c155f06305ef054"

    [[publish_theme_default.download]]
    sha256 = "00381b74d503e12fa339e2059adb28f766f78d25cc532acd5c2a1b397b7fe56f"
    url = "https://github.com/MichaelHatherly/PublishThemes/releases/download/default-0.2.0/default-0.2.0.tar.gz"
