theme = "default"
version = "0.1.0"

[html]
default_css = [
    "normalize.css",
    "tabulator_simple.min.css",
    "publish.css",
    "default.min.css",
]
default_js = [
    "versions.js",
    "lunr.js",
    "highlight.min.js",
    "tabulator.min.js",
    "julia.min.js",
    "julia-repl.min.js",
    "publish.js",
]
template = {file = "html.mustache"}

[latex]
documentclass = "article"
template = {file = "latex.mustache"}
